name: $(BuildDefinitionName)_$(SourceBranchName)_$(Date:yyyyMMdd)$(Rev:.r)

trigger: none

pool: 'Hosted Ubuntu 1604'

steps:
- script: dotnet restore
  displayName: Restoring .Net packages

- script: dotnet build --configuration Release
  displayName: Building .Net code

- task: DotNetCoreCLI@2
  displayName: Running unit tests
  inputs:
    command: test
    projects: '**/*Tests/*.csproj'
    arguments: '--configuration Release'

- script: dotnet publish WebApp --configuration Release --output publish/
  displayName: Packing application WebApp

- task: CopyFiles@2
  displayName: Copy packed application WebApp to output
  inputs:
    contents: |
      WebApp/publish/**
      !**/appsettings.Development.json
    targetFolder: '$(Build.ArtifactStagingDirectory)/'
    flattenFolders: true

- task: PublishBuildArtifacts@1
  displayName: Publishing artifacts